---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-view-role
  namespace: prod
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-view-role-binding
  namespace: prod
subjects:
  - kind: User
    name: prod-view
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-view-role
  apiGroup: rbac.authorization.k8s.io
